wifi_ssid: ""
wifi_password: ""
encryption_key: ""
ota_password: ""
# !! USE WITH CARE !!! Optional alarm code for arming/disarming if your alarm integration requires it. If left blank, the remote will attempt to arm/disarm without a code.
alarm_code: ""
