// Sample states for every screen of the remote UI. preview.py builds this
// against the real renderer (src/remote_ui_renderer.cpp) and ESPHome's display
// and font code, and writes one PBM per scenario.
#include <cstdlib>
#include <cstring>
#include <deque>
#include <functional>
#include <string>
#include <vector>

#include "esphome/components/font/font.h"
#include "remote_ui_renderer.h"
#include "sim_display.h"

using namespace esphome;
font::Font *sim_font(const char *name);  // generated by preview.py

static std::deque<std::string> arena;
static const std::string *S(const char *v) {
  arena.emplace_back(v);
  return &arena.back();
}

static const uint32_t NOW = 100000;

static RemoteRenderContext base(RemoteMode mode, const char *list, const char *name, const char *state, int idx = 1,
                                int count = 5) {
  RemoteRenderContext c;
  c.mode = mode;
  c.list_title = list;
  c.item_index = idx;
  c.item_count = count;
  c.now = NOW;
  c.clock_valid = true;
  c.clock_hour = 20;
  c.clock_minute = 25;
  c.battery_monitoring_available = true;
  c.battery_percentage = 76;
  c.battery_voltage = 3.98f;
  c.selected_item_name = S(name);
  c.selected_item_state = S(state);
  c.selected_setting_detail = S("");
  // A weather entity in a US Home Assistant reports these.
  c.weather_temperature_unit = "F";
  c.weather_speed_unit = "mph";
  c.weather_pressure_unit = "inHg";
  c.weather_precipitation_unit = "in";
  return c;
}

struct Scenario {
  std::string name;
  std::function<void(SimDisplay &, const RemoteUiFonts &)> draw;
};

int main(int argc, char **argv) {
  RemoteUiFonts f;
  f.tiny = sim_font("tiny_font");
  f.small = sim_font("small_font");
  f.name = sim_font("name_font");
  f.name_small = sim_font("name_small_font");
  f.title = sim_font("title_font");
  f.large = sim_font("large_font");
  f.hero = sim_font("hero_icons");

  std::vector<Scenario> list;
  auto add = [&](const char *name, RemoteRenderContext c) {
    list.push_back({name, [c](SimDisplay &d, const RemoteUiFonts &fonts) { render_remote_ui(&d, fonts, c); }});
  };
  auto sys = [&](const char *name, RemoteSystemScreen screen, RemoteSystemScreenInfo info) {
    list.push_back(
        {name, [screen, info](SimDisplay &d, const RemoteUiFonts &fonts) { render_system_screen(&d, fonts, screen, info); }});
  };

  {  // Light on, dimmer selected
    auto c = base(REMOTE_MODE_LIGHTS, "OFFICE", "Desk Lamp", "on", 0, 4);
    c.selected_brightness_pct = 70;
    c.selected_setting_option = REMOTE_SETTING_LIGHT_DIMMER;
    add("01_light_on", c);
    c.selected_setting_option = REMOTE_SETTING_LIGHT_EFFECT;
    c.selected_setting_detail = S("colorloop");
    c.light_effect = S("colorloop");
    add("02_light_effect", c);
    auto off = base(REMOTE_MODE_LIGHTS, "OFFICE", "Ceiling Light", "off", 1, 4);
    off.selected_setting_option = REMOTE_SETTING_LIGHT_DIMMER;
    add("03_light_off", off);
  }
  {
    auto c = base(REMOTE_MODE_SWITCHES, "OFFICE", "Bambu 3D Printer", "on", 2, 4);
    add("04_switch_on", c);
    auto off = base(REMOTE_MODE_SWITCHES, "KITCHEN", "Coffee Maker", "off", 0, 3);
    off.last_switch_feedback = S("turning on...");
    off.last_switch_interaction = NOW - 500;
    add("05_switch_feedback", off);
  }
  {
    auto c = base(REMOTE_MODE_CLIMATE, "LOFT", "Hallway Thermostat", "heat", 0, 2);
    c.selected_climate_current_temp = 68;
    c.selected_climate_target_temp = 71;
    c.selected_climate_hvac_action = S("HEATING");  // the tracker upper-cases hvac_action
    c.selected_setting_option = REMOTE_SETTING_CLIMATE_TARGET;
    add("06_climate_heat", c);
    auto d = base(REMOTE_MODE_CLIMATE, "LOFT", "Hallway Thermostat", "heat_cool", 0, 2);
    d.selected_climate_current_temp = 72;
    d.selected_climate_target_temp_low = 68;
    d.selected_climate_target_temp_high = 75;
    d.selected_climate_hvac_action = S("IDLE");
    d.selected_setting_option = REMOTE_SETTING_CLIMATE_HIGH;
    add("07_climate_dual", d);
    d.selected_setting_option = REMOTE_SETTING_CLIMATE_FAN;
    d.selected_climate_fan_mode = S("auto");
    add("08_climate_fan", d);
  }
  {
    auto c = base(REMOTE_MODE_WATER_HEATERS, "UTILITY", "Water Heater", "eco", 0, 2);
    c.selected_water_heater_target_temp = 120;
    c.selected_water_heater_mode = S("eco");
    c.selected_setting_option = REMOTE_SETTING_WATER_HEATER_TARGET;
    add("09_water_heater", c);
  }
  {
    auto c = base(REMOTE_MODE_HUMIDIFIERS, "MASTER BEDROOM", "Humidifier", "on", 1, 3);
    c.selected_humidifier_current_humidity = 33;
    c.selected_humidifier_target_humidity = 50;
    c.selected_humidifier_action = S("humidifying");
    c.selected_setting_option = REMOTE_SETTING_HUMIDIFIER_HUMIDITY;
    add("10_humidifier", c);
  }
  {
    auto c = base(REMOTE_MODE_FANS, "MASTER BEDROOM", "Ceiling Fan", "on", 2, 3);
    c.selected_fan_speed_pct = 66;
    c.fan_oscillating = 1;
    c.selected_setting_option = REMOTE_SETTING_FAN_SPEED;
    add("11_fan", c);
    c.selected_setting_option = REMOTE_SETTING_FAN_OSCILLATE;
    add("12_fan_oscillate", c);
  }
  {
    auto c = base(REMOTE_MODE_COVERS, "FRONT BEDROOM", "Shade 1", "open", 0, 2);
    c.cover_has_position = true;
    c.selected_cover_position_pct = 35;
    c.selected_setting_option = REMOTE_SETTING_COVER_POSITION;
    add("13_cover_position", c);
    auto g = base(REMOTE_MODE_COVERS, "GARAGE", "Garage Door", "closed", 0, 2);
    add("14_cover_hints", g);
  }
  {
    auto c = base(REMOTE_MODE_LOCKS, "KITCHEN", "Front Side Door", "unlocked", 1, 3);
    add("15_lock_unlocked", c);
    auto h = base(REMOTE_MODE_LOCKS, "KITCHEN", "Front Side Door", "unlocked", 1, 3);
    h.hold_label = "HOLD TO LOCK";
    h.hold_progress = 60;
    add("16_lock_holding", h);
    auto l = base(REMOTE_MODE_LOCKS, "KITCHEN", "Back Door", "locked", 2, 3);
    l.last_lock_feedback = S("locked");
    l.last_lock_interaction = NOW - 1000;
    add("17_lock_feedback", l);
  }
  {
    auto c = base(REMOTE_MODE_MEDIA, "OFFICE", "Sonos ERA300", "playing", 3, 4);
    c.selected_media_title = S("Million Dollar Baby");
    c.selected_media_artist = S("Tommy Richman");
    c.selected_media_volume_pct = 46;
    c.selected_setting_option = REMOTE_SETTING_MEDIA_VOLUME;
    add("18_media_playing", c);
    c.selected_setting_option = REMOTE_SETTING_MEDIA_SOURCE;
    c.selected_media_source = S("Spotify");
    add("19_media_source", c);
    auto tv = base(REMOTE_MODE_MEDIA, "DEN", "TV", "on", 0, 2);
    tv.selected_media_device_class = S("tv");
    tv.selected_media_source = S("HDMI 1");
    tv.selected_media_volume_pct = 22;
    tv.selected_setting_option = REMOTE_SETTING_MEDIA_CHANNEL;
    add("20_media_tv", tv);
  }
  {
    auto c = base(REMOTE_MODE_SENSORS, "GARAGE", "Dehumidifier Energy", "2514.077", 0, 2);
    c.selected_sensor_unit = S("kWh");
    add("21_sensor_long", c);
    auto t = base(REMOTE_MODE_SENSORS, "OUTSIDE", "Porch Temperature", "41.2", 1, 2);
    t.selected_sensor_unit = S("°F");
    add("22_sensor_temp", t);
    auto b = base(REMOTE_MODE_SENSORS, "ATTIC", "Mousetrap 1", "off", 0, 1);
    add("23_sensor_binary", b);
  }
  {
    auto c = base(REMOTE_MODE_AUTOMATION, "OUTSIDE", "Christmas Lights", "off", 2, 4);
    c.automation_kind = AUTOMATION_KIND_SCRIPT;
    add("24_script", c);
    c.last_automation_feedback = S("running...");
    c.last_automation_interaction = NOW - 200;
    add("25_script_running", c);
    auto s = base(REMOTE_MODE_AUTOMATION, "LIVING ROOM", "Movie Night", "scening", 0, 2);
    s.automation_kind = AUTOMATION_KIND_SCENE;
    add("26_scene", s);
  }
  {
    auto c = base(REMOTE_MODE_ALARMS, "OUTSIDE", "House Alarm", "disarmed", 3, 4);
    c.selected_setting_option = REMOTE_SETTING_ALARM_STATE;
    c.selected_alarm_arm_mode = ALARM_ARM_MODE_AWAY;
    add("27_alarm", c);
    auto a = base(REMOTE_MODE_ALARMS, "OUTSIDE", "House Alarm", "armed_away", 3, 4);
    a.hold_label = "HOLD TO DISARM";
    a.hold_progress = 35;
    add("28_alarm_hold", a);
  }
  {
    auto c = base(REMOTE_MODE_NOTIFICATIONS, "NOTIFICATIONS",
                  "", "WARNING: Alarm tripped at the front door while the house was armed away. Check cameras.", 1, 3);
    c.selected_setting_option = REMOTE_SETTING_NOTIFICATION_MESSAGES;
    add("29_notification", c);
    auto e = base(REMOTE_MODE_NOTIFICATIONS, "NOTIFICATIONS", "", "", 0, 0);
    add("30_notifications_empty", e);
  }
  {
    auto c = base(REMOTE_MODE_WEATHER, "OUTSIDE", "WeatherFlow", "clear-night", 0, 3);
    c.selected_weather_condition = S("partlycloudy");
    c.weather_is_night = false;
    c.selected_weather_temperature = 38;
    c.selected_weather_high_temp = 45;  // from weather.get_forecasts
    c.selected_weather_low_temp = 30;
    c.selected_setting_option = REMOTE_SETTING_WEATHER_CONDITIONS;
    add("31_weather", c);
    c.selected_setting_option = REMOTE_SETTING_WEATHER_WIND_SPEED;
    c.selected_weather_wind_speed = 12;
    c.selected_weather_wind_bearing = 225;
    add("32_weather_wind", c);
    c.selected_setting_option = REMOTE_SETTING_WEATHER_HUMIDITY;
    c.selected_weather_humidity = 54;
    add("33_weather_humidity", c);
  }
  {
    auto c = base(REMOTE_MODE_INFO, "INFO", "Time & Date", "", 0, 6);
    c.info_index = 0;
    c.clock_weekday = 3;
    c.clock_month = 4;
    c.clock_day = 7;
    add("34_info_time", c);
    auto w = base(REMOTE_MODE_INFO, "INFO", "Wireless", "", 1, 6);
    w.info_index = 1;
    w.info_primary_text = "HomeWiFi";
    w.info_secondary_text = "-61 dBm";
    w.wifi_rssi = -61;
    add("35_info_wifi", w);
    auto b = base(REMOTE_MODE_INFO, "INFO", "Battery", "", 4, 6);
    b.info_index = 4;
    add("36_info_battery", b);
    auto v = base(REMOTE_MODE_INFO, "INFO", "Version", "", 5, 6);
    v.info_index = 5;
    v.info_primary_text = "3.11";
    v.info_secondary_text = "2026.9.0";
    add("37_info_version", v);
    auto n = base(REMOTE_MODE_INFO, "INFO", "Network", "", 2, 6);
    n.info_index = 2;
    n.info_primary_text = "192.168.0.84";
    add("38_info_network", n);
    auto k = base(REMOTE_MODE_LIGHTS, "OFFICE", "Desk Lamp", "on", 0, 4);
    k.selected_brightness_pct = 70;
    k.contrast = 6;
    k.last_contrast_interaction = NOW - 100;
    add("39_contrast", k);
  }
  {  // Edge cases
    auto c = base(REMOTE_MODE_LIGHTS, "UPSTAIRS", "Upstairs Hallway Ceiling Light Group", "", 2, 12);
    add("50_light_syncing_longname", c);
    auto n = base(REMOTE_MODE_LIGHTS, "PORCH", "Porch Light", "on", 0, 1);
    n.battery_monitoring_available = false;
    n.clock_valid = false;
    add("51_light_onoff_only", n);
    auto t = base(REMOTE_MODE_CLIMATE, "BASEMENT", "Mini Split", "cool", 0, 3);
    t.selected_climate_current_temp = 77;
    t.selected_climate_target_temp = 74;
    t.selected_climate_hvac_action = S("cooling");
    t.selected_setting_option = REMOTE_SETTING_CLIMATE_TARGET;
    t.climate_target_focus = 1;
    t.climate_target_focus_value = 73;
    t.last_climate_target_focus_interaction = NOW - 300;
    add("52_climate_cool_adjusting", t);
    auto o = base(REMOTE_MODE_CLIMATE, "BASEMENT", "Mini Split", "off", 0, 3);
    o.selected_climate_current_temp = 64;
    o.selected_setting_option = REMOTE_SETTING_CLIMATE_STATE;
    o.toast_text = S("ALREADY OFF");
    o.toast_at = NOW - 200;
    add("53_climate_off_toast", o);
    auto a = base(REMOTE_MODE_CLIMATE, "BASEMENT", "Mini Split", "auto", 0, 3);
    a.selected_climate_current_temp = 70;
    a.selected_climate_target_temp = 70;
    a.selected_climate_hvac_action = S("preheating");
    a.selected_setting_option = REMOTE_SETTING_CLIMATE_PRESETS;
    a.selected_climate_preset = S("comfort");
    add("54_climate_auto_preset", a);
    auto u = base(REMOTE_MODE_CLIMATE, "BASEMENT", "Mini Split", "", 0, 3);
    u.selected_setting_option = REMOTE_SETTING_CLIMATE_STATE;
    add("55_climate_syncing", u);
    auto w = base(REMOTE_MODE_WATER_HEATERS, "UTILITY", "Water Heater", "electric", 0, 2);
    w.selected_water_heater_target_temp = 125;
    w.selected_water_heater_mode = S("electric");
    w.selected_water_heater_away = S("on");
    w.selected_setting_option = REMOTE_SETTING_WATER_HEATER_AWAY;
    add("56_water_heater_electric_away", w);
    auto h = base(REMOTE_MODE_HUMIDIFIERS, "NURSERY", "Humidifier", "off", 0, 2);
    h.selected_humidifier_current_humidity = 41;
    h.selected_humidifier_target_humidity = 45;
    h.selected_humidifier_action = S("off");
    h.selected_setting_option = REMOTE_SETTING_HUMIDIFIER_MODE;
    h.selected_humidifier_mode = S("sleep");
    add("57_humidifier_off_mode", h);
    auto fo = base(REMOTE_MODE_FANS, "PORCH", "Ceiling Fan", "off", 1, 2);
    fo.selected_setting_option = REMOTE_SETTING_FAN_SPEED;
    add("58_fan_off", fo);
    auto fd = base(REMOTE_MODE_FANS, "PORCH", "Ceiling Fan", "on", 1, 2);
    fd.selected_fan_speed_pct = 100;
    fd.selected_setting_option = REMOTE_SETTING_FAN_DIRECTION;
    fd.selected_setting_detail = S("reverse");
    add("59_fan_direction", fd);
    auto cv = base(REMOTE_MODE_COVERS, "GARAGE", "Garage Door", "opening", 0, 2);
    cv.last_cover_feedback = S("opening...");
    cv.last_cover_interaction = NOW - 800;
    add("60_cover_opening", cv);
    auto ct = base(REMOTE_MODE_COVERS, "OFFICE", "Venetian Blind", "open", 1, 2);
    ct.cover_has_position = true;
    ct.selected_cover_position_pct = 100;
    ct.cover_tilt_pct = 45;
    ct.selected_setting_option = REMOTE_SETTING_COVER_TILT;
    add("61_cover_tilt", ct);
    auto lj = base(REMOTE_MODE_LOCKS, "GARAGE", "Side Door", "jammed", 0, 1);
    lj.last_lock_feedback = S("jammed");
    lj.last_lock_interaction = NOW - 2000;
    add("62_lock_jammed", lj);
    auto mp = base(REMOTE_MODE_MEDIA, "KITCHEN", "Kitchen Speaker", "paused", 1, 2);
    mp.selected_media_title = S("A Very Long Podcast Episode Title That Keeps Going");
    mp.selected_media_artist = S("Some Podcast Network");
    mp.selected_media_volume_pct = 0;
    mp.selected_setting_option = REMOTE_SETTING_MEDIA_SHUFFLE;
    mp.selected_media_shuffle = S("true");
    add("63_media_paused_long", mp);
    auto mi = base(REMOTE_MODE_MEDIA, "KITCHEN", "Kitchen Speaker", "idle", 1, 2);
    mi.selected_setting_option = REMOTE_SETTING_MEDIA_REPEAT;
    mi.selected_media_repeat = S("all");
    add("64_media_idle", mi);
    auto tv = base(REMOTE_MODE_MEDIA, "DEN", "Living Room TV", "off", 0, 2);
    tv.selected_media_device_class = S("tv");
    tv.selected_setting_option = REMOTE_SETTING_MEDIA_VOLUME;
    tv.selected_media_volume_pct = -1;  // an off TV reports no volume
    add("65_tv_off", tv);
    auto sw = base(REMOTE_MODE_SENSORS, "POWER", "Office Power", "1520", 0, 3);
    sw.selected_sensor_unit = S("W");
    add("66_sensor_watts", sw);
    auto st = base(REMOTE_MODE_SENSORS, "PEOPLE", "Dryer Status", "Running cycle", 1, 3);
    add("67_sensor_text", st);
    auto au = base(REMOTE_MODE_AUTOMATION, "NIGHT", "Bedtime Routine", "on", 0, 2);
    au.automation_kind = AUTOMATION_KIND_AUTOMATION;
    au.hold_label = "HOLD TO RUN";
    au.hold_progress = 80;
    add("68_automation_hold", au);
    auto at = base(REMOTE_MODE_ALARMS, "OUTSIDE", "House Alarm", "triggered", 3, 4);
    at.selected_setting_option = REMOTE_SETTING_ALARM_STATE;
    at.selected_alarm_arm_mode = ALARM_ARM_MODE_NIGHT;
    add("69_alarm_triggered", at);
    auto ar = base(REMOTE_MODE_ALARMS, "OUTSIDE", "House Alarm", "arming", 3, 4);
    ar.last_alarm_feedback = S("arming...");
    ar.last_alarm_interaction = NOW - 1500;
    add("70_alarm_arming", ar);
    auto nt = base(REMOTE_MODE_NOTIFICATIONS, "NOTIFICATIONS", "", "Washer done.", 0, 1);
    nt.selected_setting_option = REMOTE_SETTING_NOTIFICATION_MESSAGES;
    add("71_notification_short", nt);
    auto nw = base(REMOTE_MODE_NOTIFICATIONS, "NOTIFICATIONS", "",
                   "Update available: https://www.home-assistant.io/blog/2026/10/01/release-202610/ is ready", 1, 2);
    add("72_notification_url", nw);
    auto wr = base(REMOTE_MODE_WEATHER, "OUTSIDE", "Home Forecast", "rainy", 0, 1);
    wr.selected_weather_condition = S("rainy");
    wr.weather_is_night = true;
    wr.selected_weather_temperature = -4;
    wr.selected_setting_option = REMOTE_SETTING_WEATHER_PRESSURE;
    wr.selected_weather_pressure = 29.92f;
    add("73_weather_rain_pressure", wr);
    auto wu = base(REMOTE_MODE_WEATHER, "OUTSIDE", "Home Forecast", "sunny", 0, 1);
    wu.selected_weather_condition = S("sunny");
    wu.selected_weather_temperature = 88;
    wu.selected_weather_high_temp = 91;
    wu.selected_weather_low_temp = 70;
    wu.selected_setting_option = REMOTE_SETTING_WEATHER_UV_INDEX;
    wu.selected_weather_uv_index = 7.2f;
    add("74_weather_uv", wu);
    auto wb = wu;
    wb.selected_setting_option = REMOTE_SETTING_WEATHER_WIND_BEARING;
    wb.selected_weather_wind_bearing = 30;
    add("75_weather_bearing", wb);
    auto ws = base(REMOTE_MODE_WEATHER, "OUTSIDE", "Home Forecast", "", 0, 1);
    add("76_weather_syncing", ws);
    auto dev = base(REMOTE_MODE_INFO, "INFO", "Device Name", "", 3, 6);
    dev.info_index = 3;
    dev.info_primary_text = "esphome-remote";
    dev.info_secondary_text = "ESPHome Remote";
    add("77_info_device", dev);
    auto nb = base(REMOTE_MODE_INFO, "INFO", "Battery", "", 4, 6);
    nb.info_index = 4;
    nb.battery_monitoring_available = false;
    add("78_info_no_battery", nb);

    // States behind fixed display bugs.
    auto ton = base(REMOTE_MODE_SWITCHES, "KITCHEN", "Coffee Maker", "turning_on", 0, 3);
    add("79_switch_turning_on", ton);
    auto tvs = base(REMOTE_MODE_MEDIA, "DEN", "Living Room TV", "", 0, 2);
    tvs.selected_media_device_class = S("tv");
    add("80_tv_syncing", tvs);
    auto hn = base(REMOTE_MODE_HUMIDIFIERS, "NURSERY", "Humidifier", "on", 0, 1);
    hn.selected_humidifier_target_humidity = 45;  // no humidity sensor: no current reading
    hn.selected_humidifier_action = S("humidifying");
    hn.selected_setting_option = REMOTE_SETTING_HUMIDIFIER_HUMIDITY;
    add("81_humidifier_no_sensor", hn);
    auto fan_off = base(REMOTE_MODE_FANS, "MASTER BEDROOM", "Ceiling Fan", "off", 2, 3);
    fan_off.fan_oscillating = 1;  // Home Assistant keeps oscillating while off
    add("82_fan_off_oscillating", fan_off);
    auto co = base(REMOTE_MODE_COVERS, "FRONT BEDROOM", "Shade 1", "opening", 0, 2);
    co.cover_has_position = true;
    co.selected_cover_position_pct = 40;
    co.selected_setting_option = REMOTE_SETTING_COVER_POSITION;
    add("83_cover_opening", co);
    auto se = base(REMOTE_MODE_WEATHER, "OUTSIDE", "Home Forecast", "sunny", 0, 1);
    se.selected_weather_condition = S("sunny");
    se.weather_is_night = true;  // a June evening: still sunny, so still the sun
    se.selected_weather_temperature = 81;
    add("84_weather_sunny_evening", se);
    auto pr = se;
    pr.selected_setting_option = REMOTE_SETTING_WEATHER_PRECIPITATION;
    pr.selected_weather_precipitation = 0.04f;
    add("85_weather_precip_inches", pr);
    auto cc = base(REMOTE_MODE_CLIMATE, "LOFT", "Heat Pump", "heat", 0, 2);
    cc.temperature_unit = "C";
    cc.selected_climate_current_temp = 20.8f;
    cc.selected_climate_target_temp = 21.5f;
    cc.selected_climate_hvac_action = S("IDLE");
    cc.selected_setting_option = REMOTE_SETTING_CLIMATE_TARGET;
    add("86_climate_half_degree", cc);
    auto mv = base(REMOTE_MODE_MEDIA, "KITCHEN", "Kitchen Speaker", "off", 1, 2);
    mv.selected_setting_option = REMOTE_SETTING_MEDIA_VOLUME;
    mv.selected_media_volume_pct = -1;
    add("87_media_volume_unknown", mv);

    // Entities Home Assistant reports as unavailable.
    auto lu = base(REMOTE_MODE_LIGHTS, "OFFICE", "Desk Lamp", "unavailable", 0, 4);
    add("88_light_unavailable", lu);
    auto ku = base(REMOTE_MODE_LOCKS, "ENTRY", "Front Door", "unavailable", 0, 2);
    add("89_lock_unavailable", ku);
    auto su = base(REMOTE_MODE_SWITCHES, "KITCHEN", "Coffee Maker", "unavailable", 0, 3);
    add("90_switch_unavailable", su);
    auto cu = base(REMOTE_MODE_CLIMATE, "LOFT", "Hallway Thermostat", "unavailable", 0, 2);
    cu.selected_climate_current_temp = 68;  // the last reading, which no longer holds
    add("91_climate_unavailable", cu);
    auto toast = base(REMOTE_MODE_LOCKS, "ENTRY", "Front Door", "unavailable", 0, 2);
    toast.toast_text = S("UNAVAILABLE");
    toast.toast_at = NOW - 500;
    add("92_unavailable_toast", toast);

    // States Home Assistant reports that the remote used to show badly.
    auto sf = base(REMOTE_MODE_SENSORS, "LOFT", "Office Temperature", "23.6000003814697", 0, 3);
    sf.selected_sensor_unit = S("°C");  // an ESPHome sensor's float, as Home Assistant writes it
    add("93_sensor_float", sf);
    auto sm = base(REMOTE_MODE_SENSORS, "OUTSIDE", "Air Quality PM2.5", "12.4000000953674", 1, 3);
    sm.selected_sensor_unit = S("\xC2\xB5g/m\xC2\xB3");  // Home Assistant's "μg/m³", normalized
    add("94_sensor_micro", sm);
    auto su2 = base(REMOTE_MODE_SENSORS, "PEOPLE", "Last Motion", "unknown", 2, 3);
    add("95_sensor_unknown", su2);
    auto se2 = base(REMOTE_MODE_SENSORS, "POWER", "Car Charger", "not_charging", 1, 3);
    add("96_sensor_enum", se2);
    auto lo = base(REMOTE_MODE_LOCKS, "ENTRY", "Front Door", "open", 0, 2);
    add("97_lock_open", lo);
    auto wun = base(REMOTE_MODE_WEATHER, "OUTSIDE", "Home Forecast", "unavailable", 0, 1);
    wun.selected_weather_condition = S("unavailable");
    add("98_weather_unavailable", wun);
    auto wk = base(REMOTE_MODE_WEATHER, "OUTSIDE", "Home Forecast", "unknown", 0, 1);
    wk.selected_weather_condition = S("unknown");
    wk.selected_weather_temperature = 61;
    add("99_weather_unknown_condition", wk);
    auto am = base(REMOTE_MODE_ALARMS, "OUTSIDE", "House Alarm", "disarmed", 3, 4);
    am.selected_setting_option = REMOTE_SETTING_ALARM_STATE;
    am.selected_alarm_arm_mode = ALARM_ARM_MODE_NIGHT;  // picked on another panel
    am.alarm_supported_features = 3;                    // home and away only
    add("9a_alarm_home_away_only", am);
    auto wh = base(REMOTE_MODE_WATER_HEATERS, "UTILITY", "Water Heater", "", 0, 2);
    add("9b_water_heater_syncing", wh);
    auto cm = base(REMOTE_MODE_CLIMATE, "LOFT", "Hallway Thermostat", "unknown", 0, 2);
    cm.selected_climate_current_temp = 70;
    cm.selected_setting_option = REMOTE_SETTING_CLIMATE_STATE;
    add("9c_climate_unknown_mode", cm);
    auto cu2 = base(REMOTE_MODE_COVERS, "GARAGE", "Awning", "unknown", 1, 2);
    add("9d_cover_unknown", cu2);
    auto ww = base(REMOTE_MODE_WEATHER, "OUTSIDE", "Home Forecast", "windy", 0, 1);
    ww.selected_weather_condition = S("windy");
    ww.selected_weather_temperature = -0.3f;
    ww.weather_temperature_unit = "C";
    ww.weather_speed_unit = "km/h";
    ww.selected_weather_wind_speed = 31;
    ww.selected_weather_wind_bearing = 315;
    ww.selected_setting_option = REMOTE_SETTING_WEATHER_WIND_SPEED;
    add("9e_weather_metric_wind", ww);
  }
  {  // Entity types added later, and settings added to existing ones.
    auto ib = base(REMOTE_MODE_SWITCHES, "HOUSE", "Guest Mode", "on", 0, 7);
    add("a0_input_boolean", ib);
    auto bt = base(REMOTE_MODE_AUTOMATION, "HOUSE", "TV Power", "ready", 1, 7);
    bt.automation_kind = AUTOMATION_KIND_BUTTON;
    add("a1_button", bt);
    bt.hold_label = "HOLD TO PRESS";
    bt.hold_progress = 60;
    add("a2_button_hold", bt);
    auto ph = base(REMOTE_MODE_SENSORS, "HOUSE", "Alex", "home", 6, 7);
    ph.sensor_is_presence = true;
    add("a3_person_home", ph);
    auto pa = ph;
    pa.selected_item_state = S("not_home");
    add("a4_person_away", pa);
    auto pz = ph;
    pz.selected_item_state = S("Work");
    add("a5_person_zone", pz);
    auto nb = base(REMOTE_MODE_INPUTS, "HOUSE", "Speaker Bass", "4.0", 2, 7);
    nb.input_value = 4;
    nb.input_min = -10;
    nb.input_max = 10;
    nb.input_unit = S("dB");
    nb.selected_setting_option = REMOTE_SETTING_INPUT_VALUE;
    add("a6_number", nb);
    auto sl = base(REMOTE_MODE_INPUTS, "HOUSE", "House Mode", "Movie Night", 3, 7);
    sl.input_is_select = true;
    sl.selected_setting_option = REMOTE_SETTING_INPUT_OPTION;
    add("a7_select", sl);
    auto vc = base(REMOTE_MODE_VACUUMS, "HOUSE", "Robot Vacuum", "cleaning", 4, 7);
    vc.selected_setting_option = REMOTE_SETTING_VACUUM_ACTIONS;
    vc.vacuum_fan_speed = S("standard");
    add("a8_vacuum_cleaning", vc);
    auto vd = vc;
    vd.selected_item_state = S("docked");
    vd.selected_setting_option = REMOTE_SETTING_VACUUM_FAN_SPEED;
    vd.vacuum_fan_speed = S("max");
    add("a9_vacuum_fan", vd);
    auto mw = base(REMOTE_MODE_VACUUMS, "GARDEN", "Lawn Mower", "mowing", 0, 2);
    mw.vacuum_is_mower = true;
    mw.selected_setting_option = REMOTE_SETTING_VACUUM_ACTIONS;
    add("aa_mower", mw);
    auto ta = base(REMOTE_MODE_TIMERS, "KITCHEN", "Pasta Timer", "active", 6, 7);
    ta.timer_seconds = 252;
    add("ab_timer_active", ta);
    auto tp = ta;
    tp.selected_item_state = S("paused");
    tp.timer_seconds = 3725;
    add("ac_timer_paused", tp);
    auto ti = ta;
    ti.selected_item_state = S("idle");
    ti.timer_seconds = 300;
    add("ad_timer_idle", ti);
    auto vo = base(REMOTE_MODE_COVERS, "HOUSE", "Garden Water", "open", 5, 7);
    vo.cover_is_valve = true;
    add("ae_valve_open", vo);
    auto vp = vo;
    vp.selected_item_state = S("closed");
    vp.cover_has_position = true;
    vp.selected_cover_position_pct = 0;
    vp.selected_setting_option = REMOTE_SETTING_COVER_POSITION;
    add("af_valve_closed", vp);
    auto cs = base(REMOTE_MODE_COVERS, "GARAGE", "Garage Door", "closing", 0, 2);
    cs.cover_stoppable = true;
    add("ag_cover_stop", cs);
    auto lw = base(REMOTE_MODE_LIGHTS, "OFFICE", "Desk Lamp", "on", 0, 4);
    lw.selected_brightness_pct = 70;
    lw.selected_setting_option = REMOTE_SETTING_LIGHT_WARMTH;
    lw.light_color_temp_kelvin = 2700;
    lw.light_min_kelvin = 2000;
    lw.light_max_kelvin = 6500;
    add("ah_light_warmth", lw);
    auto cm = base(REMOTE_MODE_CLIMATE, "LOFT", "Hallway Thermostat", "heat", 0, 2);
    cm.selected_climate_current_temp = 68;
    cm.selected_climate_target_temp = 71;
    cm.selected_climate_hvac_action = S("IDLE");
    cm.selected_setting_option = REMOTE_SETTING_CLIMATE_STATE;
    cm.climate_mode_count = 4;
    add("ai_climate_mode", cm);
    auto mm = base(REMOTE_MODE_MEDIA, "KITCHEN", "Kitchen Speaker", "playing", 1, 2);
    mm.selected_media_title = S("Clair de Lune");
    mm.selected_media_artist = S("Claude Debussy");
    mm.media_muted = 1;
    mm.selected_setting_option = REMOTE_SETTING_MEDIA_MUTE;
    add("aj_media_mute", mm);
    auto tm = base(REMOTE_MODE_MEDIA, "DEN", "Living Room TV", "on", 0, 2);
    tm.selected_media_device_class = S("tv");
    tm.selected_media_source = S("HDMI 1");
    tm.media_muted = 1;
    tm.selected_setting_option = REMOTE_SETTING_MEDIA_VOLUME;
    tm.selected_media_volume_pct = 25;
    add("ak_tv_muted", tm);

    // TV remotes, events, lock OPEN, light COLOR and climate SWING.
    auto rk = base(REMOTE_MODE_REMOTES, "DEN", "Apple TV", "on", 2, 3);
    rk.remote_has_commands = true;
    rk.remote_activity = S("");
    rk.selected_setting_option = REMOTE_SETTING_REMOTE_KEYS;
    add("b0_remote_keys", rk);
    auto rn = rk;
    rn.selected_setting_option = REMOTE_SETTING_REMOTE_NAVIGATE;
    add("b1_remote_navigate", rn);
    auto rf = rn;
    rf.remote_key_flash = REMOTE_KEY_DOWN;
    rf.remote_key_flash_at = NOW - 50;
    add("b2_remote_down", rf);
    auto ro = rn;
    ro.remote_key_flash = REMOTE_KEY_SELECT;
    ro.remote_key_flash_at = NOW - 50;
    add("b3_remote_ok", ro);
    auto rb = rk;
    rb.remote_key_flash = REMOTE_KEY_BACK;
    rb.remote_key_flash_at = NOW - 50;
    add("b4_remote_back", rb);
    auto ra = base(REMOTE_MODE_REMOTES, "LIVING ROOM", "Harmony Hub", "on", 0, 3);
    ra.remote_activity = S("Watch TV");
    ra.selected_setting_option = REMOTE_SETTING_REMOTE_ACTIVITY;
    add("b5_remote_activity", ra);
    auto rx = base(REMOTE_MODE_REMOTES, "LIVING ROOM", "Harmony Hub", "off", 0, 3);
    rx.remote_activity = S("");
    add("b6_remote_no_commands", rx);
    auto ev = base(REMOTE_MODE_SENSORS, "HOUSE", "Front Doorbell", "8:41 PM", 2, 7);
    ev.sensor_is_event = true;
    ev.event_type = S("ring");
    ev.event_device_class = S("doorbell");
    ev.event_seconds_ago = 4 * 60 + 12;
    add("b7_event_doorbell", ev);
    auto eb = ev;
    eb.selected_item_name = S("Hallway Button");
    eb.event_type = S("double_press");
    eb.event_device_class = S("button");
    eb.event_seconds_ago = 30;
    add("b8_event_button", eb);
    auto en = ev;
    en.selected_item_state = S("unknown");
    add("b9_event_none", en);
    auto lo = base(REMOTE_MODE_LOCKS, "ENTRY", "Front Door", "locked", 1, 3);
    lo.selected_setting_option = REMOTE_SETTING_LOCK_OPEN;
    add("ba_lock_open_setting", lo);
    auto lp = lo;
    lp.selected_item_state = S("open");
    add("bb_lock_opened", lp);
    auto lc = base(REMOTE_MODE_LIGHTS, "LIVING ROOM", "Accent Strip", "on", 1, 5);
    lc.selected_brightness_pct = 80;
    lc.selected_setting_option = REMOTE_SETTING_LIGHT_COLOR;
    lc.light_color_name = "BLUE";
    add("bc_light_color", lc);
    auto sw = base(REMOTE_MODE_CLIMATE, "BEDROOM", "Mini Split", "cool", 0, 2);
    sw.selected_climate_current_temp = 76;
    sw.selected_climate_target_temp = 72;
    sw.selected_climate_hvac_action = S("COOLING");
    sw.selected_setting_option = REMOTE_SETTING_CLIMATE_SWING;
    sw.climate_swing_mode = S("vertical");
    add("bd_climate_swing", sw);

    // Waking: the frame from before sleep, without its clock, while the
    // remote connects (what boot_screen and update_display draw).
    auto snap = base(REMOTE_MODE_LIGHTS, "OFFICE", "Desk Lamp", "on", 0, 4);
    snap.selected_brightness_pct = 70;
    snap.selected_setting_option = REMOTE_SETTING_LIGHT_DIMMER;
    for (const char *status :
         {"WAITING FOR WI-FI\u2026", "CONNECTING\u2026", "SYNCING\u2026", "WAITING TO SEND\u2026", "SENDING\u2026"}) {
      const char *kind = status[8] == 'F'   ? "wifi"
                         : status[8] == 'T' ? "queued"
                         : status[0] == 'C' ? "api"
                         : status[1] == 'Y' ? "sync"
                                            : "sending";
      std::string name = std::string("al_snapshot_") + kind;
      list.push_back({name, [snap, status](SimDisplay &d, const RemoteUiFonts &fonts) {
                        render_remote_ui(&d, fonts, snap);
                        int clock_x = 0, clock_w = 0;
                        remote_ui_header_clock_box(&clock_x, &clock_w);
                        if (clock_w > 0) {
                          d.filled_rectangle(clock_x, 0, clock_w, 9, display::COLOR_OFF);
                        }
                        render_snapshot_status(&d, fonts, status);
                      }});
    }
  }
  {
    RemoteSystemScreenInfo info;
    info.version = "3.11";
    sys("40_sys_connecting", REMOTE_SCREEN_CONNECTING_WIFI, info);
    sys("41_sys_api", REMOTE_SCREEN_CONNECTING_API, info);
    sys("42_sys_api_lost", REMOTE_SCREEN_API_LOST, info);
    RemoteSystemScreenInfo batt;
    batt.battery_voltage = 3.41f;
    sys("43_sys_low_battery", REMOTE_SCREEN_LOW_BATTERY, batt);
    sys("44_sys_power_off", REMOTE_SCREEN_POWERING_OFF, info);
    RemoteSystemScreenInfo hold;
    hold.progress = 40;
    sys("45_sys_hold_reboot", REMOTE_SCREEN_HOLD_TO_REBOOT, hold);
    sys("46_sys_rebooting", REMOTE_SCREEN_REBOOTING, info);
  }

  const char *out_dir = argc > 1 ? argv[1] : ".";
  bool stats = argc > 2 && strcmp(argv[2], "--stats") == 0;
  for (auto &sc : list) {
    SimDisplay d;
    sc.draw(d, f);
    std::string path = std::string(out_dir) + "/" + sc.name + ".pbm";
    if (!d.save_pbm(path.c_str())) {
      fprintf(stderr, "cannot write %s\n", path.c_str());
      return 1;
    }
    if (stats) {
      printf("%-32s pixel calls %6ld  lit pixels %5d\n", sc.name.c_str(), d.pixel_calls, d.lit_pixels());
    }
  }
  printf("%zu frames\n", list.size());
  return 0;
}
