// Hostile input for every screen of the remote UI. preview.py --stress builds
// this with AddressSanitizer and UndefinedBehaviorSanitizer, then draws every
// mode and every setting footer with empty, oversized and malformed text, text
// that a fixed-size buffer cuts in the middle of a character, and NaN or
// out-of-range numbers. An out-of-bounds read, a NaN cast or any other undefined
// behaviour stops the run with a report; on the remote the same bug would draw
// garbage or crash.
#include <cmath>
#include <cstdio>
#include <string>
#include <vector>

#include "esphome/components/font/font.h"
#include "remote_ui_renderer.h"
#include "sim_display.h"

using namespace esphome;
font::Font *sim_font(const char *name);  // generated by preview.py

namespace {

struct Reading {
  float value;
  int percent;
};

std::vector<std::string> hostile_text() {
  std::vector<std::string> text = {
      "",
      " ",
      "on",
      "unknown",
      "unavailable",
      std::string(300, 'W'),
      "Caf\xC3\xA9 \xC3\x9Cn\xC3\xAF \xCE\x95\xCE\xBB \xE6\x97\xA5\xE6\x9C\xAC \xF0\x9F\x8E\x89",
      "\xC3",              // a character cut after its first byte
      "abc\xE2\x82",       // ... after its second
      "abc\xF0\x9F",
      "\x80\x80\x80\x80",  // continuation bytes with no first byte
      "\xFF\xFE\xFD",      // bytes that never appear in UTF-8
      "line1\nline2\n\n\n\nline6\nline7\nline8\nline9",
      "-12345678901234567890.5",
  };
  std::string words;
  for (int i = 0; i < 40; i++) {
    words += "word" + std::to_string(i) + " ";
  }
  text.push_back(words);
  // Long runs of 2-, 3- and 4-byte characters behind 0-7 ASCII bytes, so every
  // fixed-size buffer cuts one of them in the middle of a character.
  for (const char *wide : {"\xC3\xA9", "\xE2\x80\xA6", "\xF0\x9F\x8E\x89"}) {
    std::string run;
    for (int i = 0; i < 40; i++) {
      run += wide;
    }
    for (int lead = 0; lead < 8; lead++) {
      text.push_back(std::string(lead, 'x') + run);
    }
    text.push_back("21.5 " + run);  // a state that starts out numeric
  }
  return text;
}

// Fills every field from one string and one reading. The variant switches the
// flags and timestamps that pick different drawing paths (feedback, toasts,
// hold bars, focus, units).
RemoteRenderContext hostile_context(int mode, int setting, const std::string &s, Reading r, int variant) {
  const uint32_t now = 100000;
  const uint32_t just_now = now - 10;
  RemoteRenderContext c;
  c.mode = static_cast<RemoteMode>(mode);
  c.list_title = s.c_str();
  c.item_index = r.percent;
  c.item_count = variant == 0 ? 0 : r.percent;
  c.now = variant == 2 ? 0 : now;
  c.clock_valid = variant != 1;
  c.clock_hour = 23;
  c.clock_minute = 59;
  c.clock_weekday = variant + 5;
  c.clock_day = 31;
  c.clock_month = 12;
  c.battery_monitoring_available = variant != 0;
  c.battery_percentage = r.percent;
  c.battery_voltage = r.value;
  c.contrast = r.percent;
  c.last_contrast_interaction = variant == 1 ? just_now : 0;
  c.selected_setting_option = setting;
  c.selected_setting_detail = &s;
  c.toast_text = &s;
  c.toast_at = variant == 2 ? just_now : 0;
  c.hold_label = variant == 1 ? s.c_str() : nullptr;
  c.hold_progress = variant == 1 ? r.percent : -1;
  c.selected_item_name = &s;
  c.selected_item_state = &s;
  c.selected_brightness_pct = r.percent;
  c.light_effect = &s;
  c.last_switch_feedback = &s;
  c.last_switch_interaction = just_now;
  c.selected_climate_current_temp = r.value;
  c.selected_climate_target_temp = r.value;
  c.selected_climate_target_temp_low = r.value;
  c.selected_climate_target_temp_high = r.value;
  c.selected_climate_target_humidity = r.value;
  c.selected_climate_hvac_action = &s;
  c.selected_climate_fan_mode = &s;
  c.selected_climate_preset = &s;
  c.climate_target_focus = variant;
  c.climate_target_focus_value = r.value;
  c.last_climate_target_focus_interaction = just_now;
  c.selected_water_heater_target_temp = r.value;
  c.selected_water_heater_mode = &s;
  c.selected_water_heater_away = &s;
  c.selected_humidifier_target_humidity = r.value;
  c.selected_humidifier_current_humidity = r.value;
  c.selected_humidifier_action = &s;
  c.selected_humidifier_mode = &s;
  c.selected_fan_speed_pct = r.percent;
  c.fan_oscillating = variant - 1;
  c.fan_direction = &s;
  c.fan_preset = &s;
  c.selected_cover_position_pct = r.percent;
  c.cover_has_position = variant != 0;
  c.cover_tilt_pct = r.percent;
  c.last_cover_feedback = &s;
  c.last_cover_interaction = just_now;
  c.last_lock_feedback = &s;
  c.last_lock_interaction = just_now;
  c.selected_media_volume_pct = r.percent;
  c.selected_media_title = &s;
  c.selected_media_artist = &s;
  c.selected_media_device_class = &s;
  c.selected_media_source = &s;
  c.selected_media_shuffle = &s;
  c.selected_media_repeat = &s;
  c.selected_media_sound_mode = &s;
  c.last_media_power_feedback = &s;
  c.last_media_power_interaction = just_now;
  c.selected_sensor_unit = &s;
  c.automation_kind = static_cast<AutomationKind>(variant);
  c.last_automation_feedback = &s;
  c.last_automation_interaction = just_now;
  c.selected_alarm_arm_mode = variant;
  c.last_alarm_feedback = &s;
  c.last_alarm_interaction = just_now;
  c.last_notification_dismiss_interaction = variant == 1 ? just_now : 0;
  c.selected_weather_condition = &s;
  c.weather_is_night = variant == 1;
  c.selected_weather_temperature = r.value;
  c.selected_weather_humidity = r.value;
  c.selected_weather_high_temp = r.value;
  c.selected_weather_low_temp = r.value;
  c.selected_weather_wind_speed = r.value;
  c.selected_weather_wind_bearing = r.value;
  c.selected_weather_wind_gust_speed = r.value;
  c.selected_weather_pressure = r.value;
  c.selected_weather_precipitation = r.value;
  c.selected_weather_cloud_coverage = r.value;
  c.selected_weather_uv_index = r.value;
  c.selected_weather_dew_point = r.value;
  c.selected_weather_apparent_temperature = r.value;
  c.info_primary_text = s;
  c.info_secondary_text = s;
  c.wifi_rssi = r.percent;
  // Units come from settings.yaml, so only the documented choices.
  c.temperature_unit = variant == 1 ? "C" : "F";
  c.speed_unit = variant == 1 ? "KPH" : "MPH";
  c.pressure_unit = variant == 1 ? "kPa" : "hPa";
  c.precipitation_unit = variant == 1 ? "mm" : "in";
  return c;
}

}  // namespace

int main() {
  RemoteUiFonts fonts;
  fonts.tiny = sim_font("tiny_font");
  fonts.small = sim_font("small_font");
  fonts.title = sim_font("title_font");
  fonts.large = sim_font("large_font");
  fonts.hero = sim_font("hero_icons");

  long frames = 0;
  auto draw_every_screen = [&](const std::string &s, Reading r) {
    for (int mode = 0; mode < REMOTE_MODE_COUNT; mode++) {
      int pages = mode == REMOTE_MODE_INFO ? 7 : 1;  // six Info pages, plus one past the end
      for (int setting = REMOTE_SETTING_NONE; setting <= REMOTE_SETTING_WATER_HEATER_AWAY; setting++) {
        for (int variant = 0; variant < 3; variant++) {
          RemoteRenderContext c = hostile_context(mode, setting, s, r, variant);
          for (int page = 0; page < pages; page++) {
            c.info_index = page;
            SimDisplay display;
            render_remote_ui(&display, fonts, c);
            frames++;
          }
        }
      }
    }
  };

  const std::vector<std::string> text = hostile_text();
  const Reading missing_or_normal[] = {{NAN, 0}, {72.5f, 50}};
  const Reading extreme[] = {{NAN, 0},         {INFINITY, 100}, {-INFINITY, -1}, {1e9f, 1000},
                             {-1e9f, -1000}, {-40.0f, 101},   {72.5f, 50}};
  for (const std::string &s : text) {
    for (Reading r : missing_or_normal) {
      draw_every_screen(s, r);
    }
  }
  for (Reading r : extreme) {
    draw_every_screen("on", r);
  }

  for (int screen = REMOTE_SCREEN_CONNECTING_WIFI; screen <= REMOTE_SCREEN_REBOOTING; screen++) {
    for (const std::string &s : text) {
      for (Reading r : extreme) {
        RemoteSystemScreenInfo info;
        info.version = s.c_str();
        info.battery_voltage = r.value;
        info.progress = r.percent;
        SimDisplay display;
        render_system_screen(&display, fonts, static_cast<RemoteSystemScreen>(screen), info);
        frames++;
      }
    }
  }

  printf("%ld frames drawn with hostile input, no sanitizer reports\n", frames);
  return 0;
}
