script:
  - id: primary_mode_action
    then:
      - script.execute: execute_square_button_action

  - id: secondary_mode_action
    then:
      - script.execute:
          id: cycle_setting_option
          step: 1

  - id: play_pause_mode_action
    then:
      - script.execute: execute_circle_button_action

  - id: increase_mode_value
    then:
      - if:
          condition:
            lambda: 'return id(current_mode) == REMOTE_MODE_WEATHER;'
          then:
            - script.execute:
                id: cycle_setting_option
                step: 1
          else:
            - script.execute:
                id: adjust_selected_setting
                step: 1

  - id: decrease_mode_value
    then:
      - if:
          condition:
            lambda: 'return id(current_mode) == REMOTE_MODE_WEATHER;'
          then:
            - script.execute:
                id: cycle_setting_option
                step: -1
          else:
            - script.execute:
                id: adjust_selected_setting
                step: -1

  - id: reset_idle_timer
    mode: restart
    then:
      - lambda: |-
          id(last_active) = millis() / 1000;
