#pragma once

#include <string>

#include "entity_helpers_requests.h"
#include "esphome/core/time.h"

namespace esphome {

enum RemoteUiActionCommand {
  REMOTE_UI_ACTION_NONE = 0,
  REMOTE_UI_ACTION_MARK_UI,
  REMOTE_UI_ACTION_TOGGLE_LIGHT,
  REMOTE_UI_ACTION_TOGGLE_FAN,
  REMOTE_UI_ACTION_TOGGLE_CLIMATE_POWER,
  REMOTE_UI_ACTION_TOGGLE_HUMIDIFIER_POWER,
  REMOTE_UI_ACTION_CYCLE_HUMIDIFIER_MODE,
  REMOTE_UI_ACTION_TURN_ON_SWITCH,
  REMOTE_UI_ACTION_TURN_OFF_SWITCH,
  REMOTE_UI_ACTION_CLIMATE_TEMP_HIGH_UP,
  REMOTE_UI_ACTION_CLIMATE_TEMP_HIGH_DOWN,
  REMOTE_UI_ACTION_LOCK,
  REMOTE_UI_ACTION_UNLOCK,
  REMOTE_UI_ACTION_OPEN_COVER,
  REMOTE_UI_ACTION_CLOSE_COVER,
  REMOTE_UI_ACTION_SELECT_NEXT_ITEM,
  REMOTE_UI_ACTION_TRIGGER_AUTOMATION,
  REMOTE_UI_ACTION_ARM_ALARM,
  REMOTE_UI_ACTION_DISARM_ALARM,
  REMOTE_UI_ACTION_TRIGGER_ALARM,
  REMOTE_UI_ACTION_DISMISS_NOTIFICATION,
  REMOTE_UI_ACTION_SELECT_NEXT_MEDIA_SOURCE,
  REMOTE_UI_ACTION_MEDIA_PLAY_PAUSE,
  REMOTE_UI_ACTION_INCREASE_BRIGHTNESS,
  REMOTE_UI_ACTION_DECREASE_BRIGHTNESS,
  REMOTE_UI_ACTION_INCREASE_FAN_SPEED,
  REMOTE_UI_ACTION_DECREASE_FAN_SPEED,
  REMOTE_UI_ACTION_HUMIDIFIER_TARGET_UP,
  REMOTE_UI_ACTION_HUMIDIFIER_TARGET_DOWN,
  REMOTE_UI_ACTION_INCREASE_COVER_POSITION,
  REMOTE_UI_ACTION_DECREASE_COVER_POSITION,
  REMOTE_UI_ACTION_CLIMATE_TEMP_UP,
  REMOTE_UI_ACTION_CLIMATE_TEMP_DOWN,
  REMOTE_UI_ACTION_MEDIA_VOLUME_UP,
  REMOTE_UI_ACTION_MEDIA_VOLUME_DOWN,
  REMOTE_UI_ACTION_SHIFT_ALARM_MODE_FORWARD,
  REMOTE_UI_ACTION_SHIFT_ALARM_MODE_BACKWARD,
};

enum RemoteUiActionGroup {
  REMOTE_UI_ACTION_GROUP_NONE = 0,
  REMOTE_UI_ACTION_GROUP_TOGGLE,
  REMOTE_UI_ACTION_GROUP_SELECTION,
  REMOTE_UI_ACTION_GROUP_ADJUST,
  REMOTE_UI_ACTION_GROUP_SECURITY,
};

bool remote_ui_has_dual_climate_target(
    const std::string &selected_item_state, float target_temp_low, float target_temp_high);

RemoteUiActionCommand resolve_remote_mode_action_command(RemoteMode mode, int action, bool dual_climate_target);
RemoteUiActionGroup group_remote_mode_action_command(RemoteUiActionCommand command);

void populate_remote_info_text(
    int info_index, const ESPTime &time_now, const char *version, bool battery_monitoring_available,
    int battery_percentage, float battery_voltage, std::string &primary_text, std::string &secondary_text);

}  // namespace esphome
