"""PlatformIO -> ESPHome build bridge.

The real PlatformIO project for this repository is generated by ESPHome under
esphome/.esphome/build/<device>/ and cannot be reproduced by a hand-written
root platformio.ini (it pins a custom platform, dual frameworks, and build
scripts). This SCons extra_script makes the root project's default build
target simply invoke `esphome compile`, so the PlatformIO IDE build button
and `pio run` behave correctly instead of failing to resolve a platform.
"""

Import("env")

env.AddCustomTarget(
    name="esphome",
    dependencies=None,
    actions=["esphome compile esphome/remote_control.yaml"],
    title="ESPHome Compile",
    description="Build the firmware via the ESPHome toolchain",
)

env.AddCustomTarget(
    name="esphome-upload",
    dependencies=None,
    actions=["esphome run esphome/remote_control.yaml"],
    title="ESPHome Run",
    description="Build and upload the firmware via the ESPHome toolchain",
)
